export const reviews = [
    { id: "101", name: 'Flat Tummy Tea...', category: 'flat tummy tea', image: '/vibrator/flattummytea.jpg', price: 7000, discount: 9000, description:"28 days flat tummy tea Boost metabolism Suppresses appetite" },
    { id: "101", name: 'Womb Tea...', category: 'womb tea, tea', image: '/vibrator/womd tea.jpg', price: 8000, discount: 10000, description:"Benefits of Womb Tea •Balances Hormones •Warms the womb •Helps control heavy period •Relief menses pain •Detox the womb •Improves ovulation •Cleanses the system •Anaemia •Fertility issues •Dryness •Retaining youthful vigor •Detox excess hormones •Regulates menstrual cycle(irregular menses) •Relieves menstrual cramps •Strengthens uterine linings for embryo implantation •Relieves PMS symptoms •Improves ovulation ,•Suppresses fibroid growth. EVERY WOMAN NEEDS THIS TEA" },
    { id: "100", name: 'Flat Tummy Tea...', category: 'flat tummy tea', image: '/vibrator/flattummytip.jpg', price: 7000, discount: 10000, description:"Flat tummy tea with moringa aids digestion, reduces boating and suppresses appetite" },
    { id: "99", name: 'Phone Sticker...', category: 'phone stick', image: '/vibrator/phonestick.jpg', price: 2500, discount: 4000, description:"Available in different colors" },
    { id: "98", name: 'Collagen gummies...', category: 'gummie', image: '/vibrator/collegen.jpg', price: 8500, discount: 10000, description:"Collagen gummies, containing collagen peptides and often vitamins, may offer benefits for skin elasticity, hydration, and potentially reducing wrinkles." },
    { id: "97", name: 'Dynewell Butt Sryup...', category: 'Sex Toy', image: '/vibrator/dynawell.jpg', price: 6000, discount: 9000, description:"Dynewell Plus is a 100% All-Natural herbal supplement which helps enhance the size of your Buttocks and fullness of your Breasts while also slimming" },
    { id: "96", name: 'Mini influencers Light...', category: 'Sex Toy', image: '/vibrator/miniinfluncer.jpg', price: 15000, discount: 18000, description:"it has 3 colors" },
    { id: "95", name: '4pcs of Yoni Pearl...', category: 'Sex Toy', image: '/vibrator/yonipearl.jpg', price: 3500, discount: 5000, description:"Yoni pearls, sometimes called vaginal detox pearls,herbal tampons, cleansing pearls, or vaginal pearls, are basically vaginal tea bags." },
    { id: "94", name: 'Butt Booster Pills...', category: 'Sex Toy', image: '/vibrator/buttboosterpill.jpg', price: 8500, discount: 10000, description:"Firmer buttocks pill increases butt" },
    { id: "93", name: 'Rose vibrator with tongue...', category: 'Sex Toy', image: '/vibrator/bluerosevib.jpg', price: 23000, discount: 25000, description:"Rechargeable clit clicker vibrator." },
    { id: "92", name: 'MK Pure Essential oil...', category: 'Sex Toy', image: '/vibrator/mkpure.jpg', price: 6000, discount: 8000, description:"Men's penis enlargement oil" },
    { id: "91", name: 'infection test card...', category: 'Sex Toy', image: '/vibrator/infectiontest.jpg', price: 1800, discount: 10000, description:"vagina inflammation infection test card" },
    { id: "90", name: 'Max man Enlarging cream...', category: 'Sex Toy, gummie, butt', image: '/vibrator/maxman.jpg', price: 6000, discount: 10000, description:"for bigger dick size" },
    { id: "89", name: 'BBL Gummies...', category: 'gummie', image: '/vibrator/bblgummie.jpg', price: 8700, discount: 10000, description:"Bigger, Firmer and Lifting, Enlarge butt & thighs ,No weight gain or known side effects" },
    { id: "88", name: 'Whitening Gummies...', category: 'gummie', image: '/vibrator/whitenninggummie.jpg', price: 6000, discount: 9000, description:"Remove acne marsand dark spot , Protect skin from darkcircles and wrinkles, Boosts immune system" },
    {
        id: "9",
        name: "Dildo... ",
        image: "/vibrator/dildo3.jpg",
        category:"Sex Toy",
        description: "Experience satisfaction like never before with our Remote Rechargeable Dildo, designed for hands-free, mind-blowing pleasure. Featuring powerful vibrations and a sleek, body-safe silicone design, this toy offers multiple intensity levels controlled via a convenient wireless remote. Perfect for solo play or adventurous fun with a partner!",
    },
    {
        id: "2",
        name: "Lip Masks ",
        image: "/lipbeauty/lipmask.jpg",
        category:"Lip Beauty",
        description: "Give your lips the ultimate hydration and nourishment they deserve with our luxurious Lip Mask. Infused with natural ingredients and rich moisturizers, this mask works overnight to restore softness and smoothness to dry, chapped lips. Wake up to lips that feel plump, revitalized, and irresistibly smooth. Perfect for daily use or as an intensive treatment, it provides long-lasting moisture, leaving your lips kissably soft and beautifully conditioned. Suitable for all skin types.",
    },
    {
        id: "3",
        name: "Eye masks ",
        image: "/lipbeauty/facemask.jpg",
        category:"Face Beauty",
        description: "Experience satisfaction like never before with our Remote Rechargeable Dildo, designed for hands-free, mind-blowing pleasure. Featuring powerful vibrations and a sleek, body-safe silicone design, this toy offers multiple intensity levels controlled via a convenient wireless remote. Perfect for solo play or adventurous fun with a partner!",
    },
    {
        id: "4",
        name: "Lips combo ",
        image: "/lipbeauty/lipcombo.jpg",
        category:"Lip Beauty",
        description: "Experience satisfaction like never before with our Remote Rechargeable Dildo, designed for hands-free, mind-blowing pleasure. Featuring powerful vibrations and a sleek, body-safe silicone design, this toy offers multiple intensity levels controlled via a convenient wireless remote. Perfect for solo play or adventurous fun with a partner!",
    },
    {
        id: "1",
        name: "Place in Your Order",
        image: "/chan/owner.jpg",  
        category:"Aphrodisiac",
        description: "At JAY_ANNIIE's_EMPIRE, we carefully curate our collections to ensure you receive only the finest. From luxurious body enlargement essentials to sophisticated LED lights and sensual wellness products, every item is handpicked to offer the best experience.",
    },
    {
        id: "5",
        name: "Gorontula fruits",
        image: "/aphroimg/gorontulaseed.jpg",
        category:"Aphrodisiac",
        description: "Experience the natural goodness of Gorontula Seed, also known as Silky Kola — a powerful, all-natural superfood renowned for its numerous health benefits. Traditionally used for enhancing intimacy, promoting reproductive health, and improving general wellness, Gorontula Seeds are packed with antioxidants, vitamins, and minerals.",
    },
    {
        id: "6",
        name: "Smoker Detox",
        image: "/aphroimg/somker.jpg",  
        category:"Aphrodisiac",
        description: "Revitalize your respiratory system with Smoker Detox, a specially formulated blend designed to cleanse and rejuvenate your lungs from the effects of smoking. Whether you're a former smoker or currently reducing your intake, this detox helps eliminate harmful toxins and supports overall lung health.",
    },
    {
        id: "7",
        name: "Available Now",
        image: "/chan/newarr2.jpg",  
        category:"Aphrodisiac",
        description: "Revitalize your respiratory system with Smoker Detox, a specially formulated blend designed to cleanse and rejuvenate your lungs from the effects of smoking. Whether you're a former smoker or currently reducing your intake, this detox helps eliminate harmful toxins and supports overall lung health.",
    },
    {
        id: "8",
        name: "New arrivals",
        image: "/chan/newarri1.jpg",  
        category:"Aphrodisiac",
        description: "Revitalize your respiratory system with Smoker Detox, a specially formulated blend designed to cleanse and rejuvenate your lungs from the effects of smoking. Whether you're a former smoker or currently reducing your intake, this detox helps eliminate harmful toxins and supports overall lung health.",
    },
    {
        id: "1",
        name: "Place in Your Order",
        image: "/chan/owner.jpg",  
        category:"Aphrodisiac",
        description: "At JAY_ANNIIE's_EMPIRE, we carefully curate our collections to ensure you receive only the finest. From luxurious body enlargement essentials to sophisticated LED lights and sensual wellness products, every item is handpicked to offer the best experience.",
    }

];
