 export const feature = [
         { id: "1", name: 'Rose Sucker vibrator...', category: 'Sex Toy', image: '/vibrator/rosesucker.jpg', price: 22000, discount: 30000, description:"Indulge in breathtaking pleasure with the Rose Sucker Vibrator, designed to deliver powerful suction and vibration sensations right where you want them. Shaped like a beautiful rose, this elegant toy combines luxurious aesthetics with mind-blowing functionality, offering an unforgettable experience every time." },
         { id: "2", name: 'Thrusting vibrator dildo...', category: 'Sex Toy', image: '/vibrator/thrustingvibrator.jpg', price: 35000 , discount: 40000, description:'Indulge in unforgettable pleasure with our Thrusting Vibrator Dildo, a revolutionary adult toy designed to take your sensations to the next level. Engineered with powerful thrusting and vibrating capabilities, it delivers intense, rhythmic motions that perfectly mimic the real thing.'},
         { id: "3", name: 'Herbal Aphrodisiac....', category: 'Aphrodisiac', image: "/aphroimg/herbel.jpg",price: 12000 , discount: 15000, description:"Reignite desire and enhance your intimate moments with our Herbal Aphrodisiac. Crafted from a potent blend of natural herbs and powerful botanicals, it boosts libido, energy, and stamina, helping you feel more connected and confident. Perfect for rekindling romance or enhancing daily vitality."},
         { id: "4", name: 'Lip moisturizer...', category: 'Lip Beauty', image: '/lipbeauty/lipmoutualize.jpg',price: 1500 , discount: 2000, description: "Keep your lips irresistibly soft and hydrated with our Lip Moisturizer. Enriched with nourishing ingredients like Shea Butter, Vitamin E, and Jojoba Oil, it deeply moisturizes, repairs dryness, and provides a protective barrier against harsh elements. Perfect for daily use, it leaves your lips feeling smooth, supple, and beautifully refreshed. Ideal for all skin types."},
         { id: "5", name: 'Pink lips cream ...', category: 'Lip Beauty', image: '/lipbeauty/pinklipcream.jpg',price: 2500, discount: 3000, description:"Get soft, smooth, and naturally pink lips with our Pink Lips Cream. Formulated with moisturizing and nourishing ingredients, it gently lightens dark lips, restores their natural color, and keeps them hydrated all day. Perfect for enhancing your smile’s beauty with a luscious, rosy glow!" },
         { id: "6", name: '18INCHES RGB RINGLIGHT...', category: 'Ring Light', image: '/ledimg/Rgblight.jpg',price: 34000 , discount: 40000, description:"Bring your photos and videos to life with our 18-Inch RGB Ring Light. Designed for content creators, streamers, and beauty enthusiasts, this versatile ring light offers adjustable brightness, color temperatures, and 360° RGB modes for the perfect lighting every time. Elevate your work with vibrant, shadow-free illumination!"},
         { id: "7", name: 'RECHARGEABLE Penis Pump....', category: 'Sex Toy', image: "/vibrator/penispump.jpg",price: 40000 ,discount:40000, description:"For bigger dick size Rechargeable"},
         { id: "8", name: 'Remote rechargeable Dildo....', category: 'Sex Toy', image: '/vibrator/remote rechargable dildo.jpg' ,price: 45000, discount:50000, description: "Experience satisfaction like never before with our Remote Rechargeable Dildo, designed for hands-free, mind-blowing pleasure. Featuring powerful vibrations and a sleek, body-safe silicone design, this toy offers multiple intensity levels controlled via a convenient wireless remote. Perfect for solo play or adventurous fun with a partner!"},
         { id: "9", name: 'Rose Tongue licking vibrator...', category: 'Sex Toy', image: '/vibrator/rose tongue licking.jpg' ,price: 25000,discount:30000, description: "Experience pure ecstasy with our Rose Tongue Licking Vibrator, designed to deliver breathtaking pleasure like never before. Shaped like a delicate rose with a teasing, flickering tongue, this luxurious toy offers intense licking sensations and precise stimulation. Crafted from body-safe, silky-smooth silicone, it’s perfect for solo play or enhancing intimacy with a partner."},
         { id: "10", name: 'Sex dice....', category: 'Sex Toy', image: '/vibrator/sex disk.jpg',price: 10000 ,discount:15000, description: "Turn up the heat and add excitement to your intimate moments with our Sex Dice. This playful set of dice offers endless possibilities for foreplay and fun, guiding you and your partner through thrilling actions and tempting body parts. Perfect for couples looking to explore, laugh, and get closer—one roll at a time."},
         { id: "11", name: 'Wand vibrator......', category: 'Sex Toy', image: '/vibrator/wand vibrator.jpg',price: 19000 ,discount:22000, description:"Discover mind-blowing pleasure with our Wand Vibrator, designed to deliver deep, rumbly vibrations that melt away tension and awaken your senses. With its sleek, ergonomic design and multiple intensity levels, this versatile toy is perfect for solo play or enhancing intimacy with a partner."},
         { id: "12", name: 'Cranberry gummies....', category: 'Aphrodisiac', image: "/aphroimg/cranberry.jpg", price: 10000,discount:15000 , description: "Support your health with our Cranberry Gummies, a tasty and convenient way to enjoy the natural benefits of cranberries. Packed with antioxidants and essential nutrients, these gummies help promote urinary tract health, boost immunity, and enhance skin vitality. Perfect for those who want wellness with a burst of fruity goodness!"},
         { id: "14", name: 'Aphrodisiacs combo package.... ', category: 'Aphrodisiac', image: "/aphroimg/aphrodisiec.jpg",price: 20000 ,discount:25000, description:"Unleash passion and elevate intimacy with our Aphrodisiacs Combo Package. This specially curated set includes potent, natural aphrodisiacs designed to enhance arousal, boost energy, and intensify pleasure for you and your partner. Perfect for romantic nights or special occasions, it’s your secret to unforgettable experiences."},
         { id: "15", name: 'Aphrodisiacs combo package.... ', category: 'Aphrodisiac', image: "/aphroimg/aphrodisiec combo.jpg",price: 20000 ,discount:25000, description:"Unleash passion and elevate intimacy with our Aphrodisiacs Combo Package. This specially curated set includes potent, natural aphrodisiacs designed to enhance arousal, boost energy, and intensify pleasure for you and your partner. Perfect for romantic nights or special occasions, it’s your secret to unforgettable experiences."},
         { id: "16", name: 'Pussy Sugar....', category: 'Aphrodisiac', image: "/aphroimg/pussysugar.jpg",price: 2000,discount:2500 , description:"Slimy & Wetness No more dry Coochie Tightening & Sweetness "},
         { id: "17", name: 'Fertility Pill.....', category: 'Aphrodisiac', image: "/aphroimg/fertility.jpg",price: 10000 ,discount:15000 , description: "Fertility drugs generally work like natural hormones — follicle-stimulating hormone (FSH) and luteinizing hormone (LH) — to trigger ovulation. They're also used in women who ovulate to try to stimulate a better egg or an extra egg or eggs. Fertility drugs include: Clomiphene citrate"},
         
         { id: "18", name: 'Luxury Tiered Crystal Chandelier', category: 'Chandelier', image: '/chan/320x.jpg', price: 320000, discount: 350000, description:"A multi-layered masterpiece perfect for grand entrances or dining rooms." },
         { id: "19", name: 'Black Luxury Tiered Crystal Chandelier', category: 'Chandelier', image: '/chan/320kx.jpg', price: 320000 , discount: 350000, description:'A multi-layered masterpiece perfect for grand entrances or dining rooms.'},
         { id: "20", name: 'Golden Luxury Tiered Crystal Chandelier', category: 'Chandelier', image: "/chan/320k.jpg",price: 320000 , discount: 350000, description:'A multi-layered masterpiece perfect for grand entrances or dining rooms.'},
         { id: "21", name: 'Elegant Crystal Chandelier',category: 'Chandelier', image: '/chan/200k.jpg',price: 200000 , discount: 22000, description: "A breathtaking centerpiece featuring cascading crystals that sparkle in every light." },
         { id: "23", name: 'Glam Crystal Raindrop Chandelier', category: 'Chandelier', image: '/chan/125x.jpg',price: 125000, discount: 130000, description:"Featuring hanging crystals that mimic sparkling raindrops."},
         { id: "24", name: 'Vintage Candle Chandelier', category: 'Chandelier', image: "/chan/125k.jpg",price: 125000, discount: 130000, description:"Recreates the charm of candlelit chandeliers with modern convenience."},
         { id: "25", name: 'Globe Orb Chandelier', category: 'Chandelier', image: '/chan/120k.jpg' ,price: 120000, discount: 125000, description: "Spherical design combining modern aesthetics with classic charm."},
         { id: "26", name: 'Modern LED Strip Chandelie', category: 'Chandelier', image: '/chan/70x.jpg' ,price: 70000,discount:72000, description: "Flexible LED strips providing sleek, energy-efficient lighting."},
         { id: "27", name: 'Retro Glass Globe Chandelier', category: 'Chandelier', image: '/chan/70kx.jpg',price: 70000 ,discount:72000, description: "Spherical glass pendants delivering a classic yet modern appeal."},
         { id: "28", name: 'Vintage Candle Chandelier', category: 'Chandelier', image: '/chan/70k.jpg',price: 70000 ,discount:72000, description:"Unique sculptural design that serves as both light and art."},
         { id: "29", name: 'Open Frame Chandelier', category: 'Chandelier', image: "/chan/69xk.jpg", price: 69000,discount:71000 , description: " Geometric frames with exposed bulbs for a trendy industrial style."},
         { id: "30", name: 'Caged Crystal Chandelier.... ', category: 'Chandelier', image: "/chan/69x.jpg",price: 69000,discount:71000 , description:"Modern twist on classic crystal design, encased within a metal frame."},
         { id: "31", name: 'French Empire Chandelier .... ', category: 'Chandelier', image: "/chan/69kx.jpg",price: 69000,discount:71000 , description:"Ornate and luxurious, suited for formal dining rooms with high ceilings."},
         { id: "32", name: 'Mediterranean Mosaic Chandelier', category: 'Chandelier', image: "/chan/69k.jpg",price: 69000,discount:71000, description:"Intricate glasswork creating a colorful, exotic ambiance."},
         { id: "33", name: 'Modern Geometric Chandelier', category: 'Chandelier', image: "/chan/65x.jpg",price: 65000 ,discount:69000 , description: "Sleek, minimalist design with sharp angles and clean lines for a contemporary feel."},
         { id: "34", name: 'Colorful Crystal Chandelier', category: 'Chandelier', image: "/chan/65k.jpg",price: 65000 ,discount:69000 , description: "Adds a playful and luxurious touch with vibrant, multi-colored crystals."},
         
         { id: "35", name: 'Probiotic gummies', category: 'Health & Wellness', image: '/boricimg/probiotic gummer.jpg', price: 8000, discount: 9000, description:"convenient and delicious way to support gut health and overall wellness. Formulated with beneficial live bacteria, these gummies help balance the digestive system, enhance nutrient absorption, and boost immune function." },
         { id: "36", name: 'Boric acid wholesale 50pcs', category: 'Health & Wellness', image: '/boricimg/boriswholesale.jpg', price: 5500 , discount: 6000, description:'Indulge in unforgettable pleasure with our Thrusting Vibrator Dildo, a revolutionary adult toy designed to take your sensations to the next level. Engineered with powerful thrusting and vibrating capabilities, it delivers intense, rhythmic motions that perfectly mimic the real thing.'},
        
        
         { id: "37", name: 'Boric acid', category: 'Health & Wellness', image: "/boricimg/boricacid1.jpg",price: 3200 , discount: 4000, description:"A cup of boric acid•Good for VG detox • Stops inflammation and burning sensation •Clears VG itches • Balances VG PH level • Restores ceased mensuration•Bacteriostatic repair •Anti-fungal"},
         { id: "38", name: 'Boric acid', category: 'Health & Wellness', image: '/boricimg/boricacid.jpg',price: 3200 , discount: 4000, description: "First grade medical boric acid: treats yeast infections, bacterial infections, eliminates itching, burning sensation, abnormal dicharge, foul smell and after period odor"},
         { id: "39", name: 'Pink lips cream ...', category: 'Lip Beauty', image: '/lipbeauty/pinklipcream.jpg',price: 2500, discount: 3000, description:"Get soft, smooth, and naturally pink lips with our Pink Lips Cream. Formulated with moisturizing and nourishing ingredients, it gently lightens dark lips, restores their natural color, and keeps them hydrated all day. Perfect for enhancing your smile’s beauty with a luscious, rosy glow!" },
         { id: "40", name: 'Eye masks', category: 'Lip Beauty', image: '/lipbeauty/facemask.jpg',price: 900 , discount: 1500, description:"omfortable and soothing accessory designed to block out light and enhance relaxation or sleep. Made from soft, breathable materials like silk, cotton, or memory foam, eye masks provide a gentle, snug fit over the eyes."},
         { id: "41", name: 'lip combo', category: 'Lip Beauty', image: "/lipbeauty/lipcombo.jpg",price: 6500 ,discount:7000, description:"For bigger dick size Rechargeable"},
         { id: "70", name: 'face mask', category: 'Lip Beauty', image: "/lipbeauty/lipmask2.jpg",price: 900 ,discount:2000, description:"For bigger dick size Rechargeable"},
         { id: "71", name: 'lip brush', category: 'Lip Beauty', image: "/lipbeauty/lipbrush.jpg",price: 1000 ,discount:2000, description:"For bigger dick size Rechargeable"},
         { id: "42", name: 'L16 and Led 600', category: 'Led', image: '/ledimg/led16.jpg' ,price: 70000, discount:80000, description: "The L16 and LED 600 Ring Light is a versatile and high-quality lighting solution designed to enhance your photography, videography, makeup sessions, and live streaming experiences. With its powerful LED illumination and adjustable brightness settings, it provides uniform and shadow-free lighting, making it perfect for professional and personal use."},
         { id: "43", name: 'BDSM 13PCS PURPLE AND BLACK', category: 'Sex Toy', image: '/vibrator/13pcbdsmkit.jpg' ,price: 26000,discount:30000, description: "Experience pure ecstasy with our bdsm materials, designed to deliver breathtaking pleasure like never before. "},
         { id: "44", name: 'BDSM 13PCS RED AND BLACK', category: 'Sex Toy', image: '/vibrator/bdsmkit.jpg',price: 26000 ,discount:30000, description: "Experience pure ecstasy with our bdsm materials, designed to deliver breathtaking pleasure like never before. "},
         { id: "45", name: 'Dildo', category: 'Sex Toy', image: '/vibrator/dildo3.jpg',price: 25000 ,discount:30000, description:"Experience satisfying pleasure with our high-quality dildo, designed for ultimate comfort and stimulation. Made from body-safe, skin-friendly materials, it features a smooth, ergonomic shape that perfectly targets your pleasure zones. Ideal for solo play or enhancing intimacy with a partner. Easy to clean and suitable for beginners and experienced users alike."},
         { id: "46", name: '2 in 1 rose vibrator', category: 'Sex Toy', image: "/vibrator/rose vibrator.jpg", price: 10000,discount:15000 , description: "Indulge in breathtaking pleasure with the Rose Sucker Vibrator, designed to deliver powerful suction and vibration sensations right where you want them. Shaped like a beautiful rose, this elegant toy combines luxurious aesthetics with mind-blowing functionality, offering an unforgettable experience every time"},
         { id: "47", name: '16-inch  AC/DC MIST FAN ', category: "fan", image: "/fan/16 ACDC MIST FAN .jpg",price: 95000 ,discount:100000, description:"Stay cool and refreshed with our 16-inch AC/DC Mist Fan, designed to deliver powerful airflow with a refreshing mist function. This versatile fan operates on both AC power and DC battery, making it perfect for indoor and outdoor use. Featuring adjustable speed settings, wide-angle oscillation, and a large water tank for continuous misting, it ensures comfort even on the hottest days. Ideal for homes, offices, patios, or camping trips."},
         { id: "48", name: '18inch AC/DC STANDING FAN WITH SOLAR ', category: 'fan', image: "/fan/18 AcDc STANDING FAN WITH SOLAR69K.jpg",price: 69000 ,discount:90000, description:"Experience powerful cooling with our 18-inch AC/DC Standing Fan equipped with solar compatibility for uninterrupted performance. This versatile fan runs on both AC power and DC battery, with the added convenience of solar charging, making it ideal for homes, offices, outdoor activities, or areas with unstable power supply. Featuring adjustable height, multiple speed settings, and wide-angle oscillation, it delivers consistent airflow wherever you need it."},
         { id: "49", name: 'AC FAN ', category: 'fan', image: "/fan/Ac fan 120k.jpg",price: 120000,discount:150000 , description:"Keep your space cool and comfortable with our high-performance AC Fan, designed for powerful airflow and efficient cooling. Perfect for homes, offices, and commercial spaces, this fan offers adjustable speed settings, sturdy construction, and low-noise operation for a pleasant cooling experience. Built to deliver consistent performance even during the hottest days."},
         { id: "50", name: 'BBL Breast curve gummies', category: 'butt booster', image: "/boosterimg/bbl breast.jpg",price: 9000 ,discount:15000 , description: "Achieve fuller, firmer, and more defined curves with our BBL Breast Curve Gummies. Formulated with natural, potent ingredients known to support breast enhancement, firmness, and overall wellness. "},
         { id: "51", name: 'BUTT BOOSTER PILLS & HIPBUTT ENHANCING GUMMIES', category: 'butt booster', image: '/boosterimg/butt booster.jpg', price: 17000 , discount: 20000, description:'Achieve the curves you desire with our powerful combination of Butt Booster Pills and Hip-Butt Enhancing Gummies. Specially formulated with natural, high-quality ingredients known to promote fuller, rounder, and firmer buttocks and hips.'},
         
         { id: "68", name: 'Butt booster pills', category: 'butt booster', image: '/boosterimg/buttbooster1.jpg', price: 9000, discount: 10000, description:"Achieve the curves you desire with our powerful combination of Butt Booster Pills and Hip-Butt Enhancing Gummies. Specially formulated with natural, high-quality ingredients known to promote fuller, rounder, and firmer buttocks and hips." },
         { id: "52", name: 'Dick Enlargement cream', category: 'Dick booster', image: '/boosterimg/dick enlargement.jpg', price: 6000 , discount: 10000, description:'Experience enhanced size and confidence with our Dick Enlargement Cream. Formulated with potent natural ingredients designed to promote blood flow, improve firmness, and support growth over time. This fast-absorbing, non-greasy cream is ideal for regular use, helping you achieve noticeable results and improved performance. Perfect for those seeking a safe and convenient solution to enhance their manhood.'},
         { id: "53", name: 'Extreme maca butt powder', category: 'butt booster', image: "/boosterimg/Extreme maca butt powder19k.jpg",price: 19000 , discount: 20000, description:"Unlock your potential with our premium Dick Enlargement Cream, expertly formulated to enhance size, thickness, and firmness naturally. Infused with potent, skin-friendly ingredients that boost blood flow and improve stamina, this cream promotes noticeable growth with regular use. Fast-absorbing and non-greasy, it's perfect for those seeking a safe, convenient solution for better performance and heightened confidence."},
         { id: "54", name: 'HIP BUTT GUMMIES', category: 'hip and butt booster ', image: '/boosterimg/hip butt enhance.jpg',price: 8700 , discount: 10000, description: "Achieve the curves you desire with our delicious Hip Butt Gummies! Specially formulated with natural, effective ingredients to help enhance and shape your hips and buttocks."},
         { id: "55", name: 'Weight Gainer', category: 'Weight Gainer', image: '/boosterimg/WEIGHTGAINER25K.jpg',price: 25000, discount: 30000, description:"Achieve your fitness goals faster with our powerful Weight Gainer formula! Designed to support healthy weight gain, muscle growth, and enhanced energy levels, this supplement provides a rich blend of high-quality proteins, carbohydrates, and essential nutrients." },
         { id: "56", name: 'YONI INTIMATE', category: 'sex', image: '/aphroimg/WhatsApp Image 2025-03-16 at 09.16.23_dd8fbd2a.jpg',price: 34000 , discount: 40000, description:"Experience the natural care your body deserves with our Yoni Intimate formula. Specially designed to promote feminine hygiene, balance pH levels, and support overall vaginal health. Made with gentle, plant-based ingredients known for their soothing, cleansing, and moisturizing properties, this product helps you feel fresh, confident, and rejuvenated every day. Ideal for daily use to maintain comfort and wellness."},
         { id: "57", name: 'Weight gain syrup', category: 'Weight Gainer', image: "/aphroimg/weightgainsyrup.jpg",price: 4000 ,discount:5000, description:"Achieve your fitness goals faster with our powerful Weight Gainer formula! Designed to support healthy weight gain, muscle growth, and enhanced energy levels, this supplement provides a rich blend of high-quality proteins, carbohydrates, and essential nutrients."},
         { id: "58", name: '250ml Weight gain syrup', category: 'Weight Gainer', image: '/aphroimg/weightgain.jpg' ,price: 4000, discount:5000, description: "Achieve your fitness goals faster with our powerful Weight Gainer formula! Designed to support healthy weight gain, muscle growth, and enhanced energy levels, this supplement provides a rich blend of high-quality proteins, carbohydrates, and essential nutrients."},
         { id: "60", name: 'Tahina Sweetner biscuits', category: 'Sweetner biscuits', image: '/aphroimg/tahinabiscuit.jpg',price: 1000 ,discount:1500, description: "Indulge in the rich, nutty goodness of our Tahina Sweetener Biscuits. Made with premium tahini and natural sweeteners, these biscuits offer a delightful blend of creamy sesame flavor and satisfying crunch. Perfect for health-conscious snackers looking for a tasty, low-sugar treat without compromising on flavor. Enjoy them with tea, coffee, or as a wholesome snack anytime!"},
         { id: "61", name: 'Tahina & Gold fly', category: 'Sweetner biscuits', image: '/aphroimg/tahina.jpg',price: 2000 ,discount:4000, description:"Discover the ultimate duo of wellness and excitement with our Tahina & Gold Fly combination. Enjoy the rich, creamy, and nutritious goodness of Tahina, made from premium sesame seeds, packed with healthy fats, protein, and antioxidants. "},
         { id: "62", name: 'Boric acid wholesale 100pcs', category: 'Health & Wellness', image: '/boricimg/boriswholesale.jpg', price: 9000 , discount: 10000, description:'Indulge in unforgettable pleasure with our Thrusting Vibrator Dildo, a revolutionary adult toy designed to take your sensations to the next level. Engineered with powerful thrusting and vibrating capabilities, it delivers intense, rhythmic motions that perfectly mimic the real thing.'},
         { id: "63", name: 'Sweetener combo.', category: 'Sweetner biscuits', image: "/aphroimg/sweetenercombo.jpg", price: 6000,discount:15000 , description: "Enjoy the perfect balance of taste and health with our Sweetener Combo. Specially formulated to provide all the sweetness you crave without the extra calories. Made from high-quality, natural ingredients that deliver rich flavor with zero guilt."},
         { id: "64", name: 'Sweetener combo.. ', category: 'Sweetner biscuits', image: "/aphroimg/sweetener combo4k.jpg",price: 4000 ,discount:6000, description:"Enjoy the perfect balance of taste and health with our Sweetener Combo. Specially formulated to provide all the sweetness you crave without the extra calories. Made from high-quality, natural ingredients that deliver rich flavor with zero guilt."},
         { id: "65", name: 'Sweetener combo.... ', category: 'Sweetner biscuits', image: "/aphroimg/sweatner combo.jpg",price: 8000 ,discount:10000, description:"Enjoy the perfect balance of taste and health with our Sweetener Combo. Specially formulated to provide all the sweetness you crave without the extra calories. Made from high-quality, natural ingredients that deliver rich flavor with zero guilt."},
         { id: "66", name: 'Sugar lumps', category: 'Sweetner biscuits', image: "/aphroimg/sugarlumps1.jpg",price: 5000,discount:7000 , description:" Sugar Lump are lickable small cubes that help to increases sexual urge and the sweetness of ur veejay    Lick 5-10 cubes 30mins before sex"},
         { id: "67", name: 'Sachet sugar lumps', category: 'Sweetner biscuits', image: "/aphroimg/sugarlump.jpg",price: 2000 ,discount:3000 , description: "Strictly for ladies • Increases the sweetness and wetness of yoni • Helps with discomfort, burning sensation & pain during intercourse • Increases sexual desires/urges • Adds a bit of spice in the bedroom Lick  5-10 lumps 30-50 minutes before being intimate with your partner"},
        
         {
             id: "74",
             name: "Smoker Detox",
             image: "/aphroimg/somker.jpg",
             price: 8000 ,
             discount:10000 ,  
             category:"Aphrodisiac",
             description: "Revitalize your respiratory system with Smoker Detox, a specially formulated blend designed to cleanse and rejuvenate your lungs from the effects of smoking. Whether you're a former smoker or currently reducing your intake, this detox helps eliminate harmful toxins and supports overall lung health.",
         },
         {
             id: "75",
             name: "Scorpion drink",
             image: "/aphroimg/scorpiondrink1.jpg",
             price: 1000 ,
             discount:2000 ,  
             category:"sweetener",
             description: "The scorpion drink also called the emergency vaginal sweetner, which is 100% herbal and natural, to give you that sensational fantasy you want with your man.",
         },
         {
             id: "76",
             name: "Scorpion drink and Tahina",
             image: "/aphroimg/scorpion drink.jpg",
             price: 2000 ,
             discount:4000 ,  
             category:"sweetener",
             description: "The scorpion drink also called the emergency vaginal sweetner, which is 100% herbal and natural, to give you that sensational fantasy you want with your man.",
         },
         {
             id: "77",
             name: "3pcs Madu enak",
             image: "/aphroimg/madu enk.jpg",
             price: 2000 ,
             discount:4000 ,  
             category:"sweetener",
             description: "The scorpion drink also called the emergency vaginal sweetner, which is 100% herbal and natural, to give you that sensational fantasy you want with your man.",
         },
         {
             id: "78",
             name: "Juicy girl kit",
             image: "/aphroimg/juicygirlkit.jpg",
             price: 7000 ,
             discount:10000 ,  
             category:"sweetener",
             description: "The scorpion drink also called the emergency vaginal sweetner, which is 100% herbal and natural, to give you that sensational fantasy you want with your man.",
         },
         {
             id: "79",
             name: "Sweetener combo juicy girl",
             image: "/aphroimg/juicygirl.jpg",
             price: 4500 ,
             discount:7000 ,  
             category:"sweetener",
             description: "The scorpion drink also called the emergency vaginal sweetner, which is 100% herbal and natural, to give you that sensational fantasy you want with your man.",
         },
         {
             id: "80",
             name: "Huger control",
             image: "/aphroimg/hunger control.jpg",
             price: 10000 ,
             discount:12000 ,  
             category:"sweetener",
             description: "The scorpion drink also called the emergency vaginal sweetner, which is 100% herbal and natural, to give you that sensational fantasy you want with your man.",
         },
         {
             id: "81",
             name: "Gorontula syrup",
             image: "/aphroimg/gorontulasyrup.jpg",
             price: 3000 ,
             discount:7000 ,  
             category:"sweetener",
             description: "Goron tula is used to increase the libido as consumption of the fruit helps in developing strong desires for sexual intercourse and also serves as an aphrodisiac several rounds of having sex with your partner. People experiencing lowered libido, as a result of stress or other health conditions, can try goron tula.",
         },
         {
             id: "82",
             name: "Gorontula fruits",
             image: "/aphroimg/gorontulaseed.jpg",
             price: 3000 ,
             discount:7000 ,  
             category:"sweetener",
             description: "Goron tula is traditionally used as an aphrodisiac for both men and women. ",
         },
         {
             id: "83",
             name: "1L Gorontula fruits",
             image: "/aphroimg/gorontulafruit.jpg",
             price: 6000 ,
             discount:9000 ,  
             category:"sweetener",
             description: "Our herbal infection flusher is made with very unique herbs for Treatment of Various bacterial infections, Urinary tract infections, Menstrual related issues and some Sexually transmitted infections like Staphylococcus, Syphilis, Gonnorehe",
         },
         {
             id: "84",
             name: "500mL Gorontula fruits",
             image: "/aphroimg/gorontulafruit.jpg",
             price: 3500 ,
             discount:6000 ,  
             category:"sweetener",
             description: "Our herbal infection flusher is made with very unique herbs for Treatment of Various bacterial infections, Urinary tract infections, Menstrual related issues and some Sexually transmitted infections like Staphylococcus, Syphilis, Gonnorehe",
         },
     ];
 